# Generated by Django 4.1 on 2022-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperamento', models.CharField(max_length=50, verbose_name='Temperamento')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
