# Generated by Django 4.1 on 2022-10-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100, unique=True, verbose_name='Raça')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raças', to='especie.especie', verbose_name='Espécie')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Caracteristicas_Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Medio', 'Médio'), ('Grande', 'Grande'), ('Gigante', 'Gigante')], max_length=15, verbose_name='Porte')),
                ('altura', models.PositiveIntegerField(verbose_name='Altura (cm)')),
                ('comprimento', models.PositiveIntegerField(verbose_name='Comprimento (cm)')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raca.raca')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
