# Generated by Django 4.1.3 on 2022-11-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas_raca',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='raca.raca'),
        ),
    ]
