# Generated by Django 4.1 on 2022-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pele', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infec_pele',
            name='peleInfeccionada',
            field=models.CharField(max_length=100, verbose_name='Doenças na Pele'),
        ),
        migrations.AlterField(
            model_name='pele',
            name='tipo_pele',
            field=models.CharField(max_length=100, verbose_name='Tipos de pele'),
        ),
    ]
