# Generated by Django 4.1 on 2022-11-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pele', '0002_alter_infec_pele_peleinfeccionada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ectoparasitas',
            old_name='ectoparasitas',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='infec_pele',
            old_name='peleInfeccionada',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pele',
            old_name='tipo_pele',
            new_name='nome',
        ),
    ]
