# Generated by Django 4.1 on 2022-11-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_alter_ficha_doenca'),
        ('pele', '0003_rename_ectoparasitas_ectoparasitas_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Infec_pele',
            new_name='DoencaPele',
        ),
    ]
