# Generated by Django 4.1 on 2022-11-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pele', '0004_rename_infec_pele_doencapele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doencapele',
            name='nome',
        ),
        migrations.AddField(
            model_name='doencapele',
            name='doenca',
            field=models.CharField(default=1, max_length=110, verbose_name='Doenças na Pele'),
            preserve_default=False,
        ),
    ]
