# Generated by Django 4.1 on 2022-11-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pele', '0005_remove_doencapele_nome_doencapele_doenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doencapele',
            old_name='doenca',
            new_name='nome',
        ),
    ]
