# Generated by Django 4.1 on 2022-11-10 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0012_rename_ficha_anamnese'),
        ('pet', '0031_alter_pet_tutor'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Itens')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('outros', models.CharField(max_length=100, verbose_name='Outros')),
                ('anamnese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.anamnese')),
                ('banho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.banho')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.itens')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('tosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.tosa')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
