# Generated by Django 4.1.3 on 2022-11-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_itens_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='anamnese',
        ),
    ]
