# Generated by Django 4.1.3 on 2022-11-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_ficha_anamnese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='anamnese',
        ),
    ]
