# Generated by Django 4.1.3 on 2022-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_ficha_anamnese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='outros',
            field=models.CharField(max_length=100, verbose_name='Outros Itens'),
        ),
    ]
