# Generated by Django 4.1.3 on 2022-11-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_ficha_outros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('aguardando', 'aguardando'), ('aprovado', 'aprovado'), ('atendendo', 'atendendo'), ('alterado', 'alterado'), ('cancelado', 'cancelado')], default='aguardando', max_length=20, verbose_name='status')),
            ],
        ),
    ]
