# Generated by Django 4.1.3 on 2022-11-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='status',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='services.status'),
        ),
    ]
