# Generated by Django 4.1.3 on 2022-11-16 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0011_ficha_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='status',
            field=models.CharField(blank=True, choices=[('aguardando', 'aguardando'), ('aprovado', 'aprovado'), ('atendendo', 'atendendo'), ('alterado', 'alterado'), ('cancelado', 'cancelado')], default='aguardando', max_length=20, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
