# Generated by Django 4.1.3 on 2022-11-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0038_alter_pet_idade'),
        ('services', '0012_alter_ficha_funcionario_alter_ficha_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FichaBanho', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='status',
            field=models.CharField(blank=True, choices=[('aguardando', 'aguardando'), ('aprovado', 'aprovado'), ('atendendo', 'atendendo'), ('alterado', 'alterado'), ('cancelado', 'cancelado')], default='aguardando', max_length=20, verbose_name=''),
        ),
    ]
