# Generated by Django 4.1 on 2022-09-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('nome',)},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='racaCachorro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='racaGato',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='temperamento',
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.raca'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmia', 'Fêmia')], default=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.especie'),
        ),
    ]
