# Generated by Django 4.1 on 2022-09-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cliente_telefone_alter_funcionario_telefone'),
        ('sistema', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('nome',)},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='racaCachorro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='racaGato',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='pet',
            name='castracao',
            field=models.BooleanField(default=False, verbose_name='Castrado(a)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.raca'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmia', 'Fêmia')], default=True, max_length=10, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.especie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temperamento',
            field=models.CharField(choices=[('Agressivo', 'Agressivo'), ('Manso', 'Manso'), ('Anti-social', 'Anti-social'), ('Social', 'Social'), ('Agitado', 'Agitado'), ('Calmo', 'Calmo'), ('Introvertido', 'Introvertido'), ('Extrovertido', 'Extrovertido'), ('Obediente', 'Obediente'), ('Independente', 'Independente'), ('Curioso', 'Curioso'), ('Independente', 'Indiferente'), ('Ousado', 'Ousado'), ('Tímido', 'Tímido')], default=None, max_length=60, null=True, verbose_name='Temperamento'),
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso(kg)')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
