# Generated by Django 4.1 on 2022-09-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('especie',),
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('nome',)},
        ),
        migrations.CreateModel(
            name='raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100, unique=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raças', to='pet.especie')),
            ],
        ),
    ]
