# Generated by Django 4.1 on 2022-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpet',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='formpet',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Peso(kg)'),
        ),
        migrations.AlterField(
            model_name='formpet',
            name='tamanho',
            field=models.PositiveIntegerField(verbose_name='Tamanho(cm)'),
        ),
    ]
