# Generated by Django 4.1 on 2022-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_options_remove_pet_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='temperamento',
            field=models.CharField(choices=[('Agressivo', 'Agressivo'), ('Manso', 'Manso'), ('Anti-social', 'Anti-social'), ('Social', 'Social'), ('Agitado', 'Agitado'), ('Calmo', 'Calmo'), ('Introvertido', 'Introvertido'), ('Extrovertido', 'Extrovertido'), ('Obediente', 'Obediente'), ('Independente', 'Independente'), ('Curioso', 'Curioso'), ('Independente', 'Indiferente'), ('Ousado', 'Ousado'), ('Tímido', 'Tímido')], default=None, max_length=60, null=True, verbose_name='Temperamento'),
        ),
    ]
