# Generated by Django 4.1 on 2022-09-30 12:20

from django.db import migrations, models
import ecommerce.pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_especie_alter_pet_options_remove_pet_apelido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default=2, upload_to=ecommerce.pet.models.upload_image_formater),
            preserve_default=False,
        ),
    ]
