# Generated by Django 4.1 on 2022-09-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_formpet_idade_alter_formpet_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpet',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='coloracao',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='pelagem',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='racaCachorro',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='formpet',
            name='temperamento',
        ),
    ]
