# Generated by Django 4.1 on 2022-09-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0002_anamnesemodel_petmodel_delete_formpet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnesemodel',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='anamnesemodel',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
