# Generated by Django 4.1 on 2022-09-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_especie_alter_pet_options_raca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='racaCachorro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='racaGato',
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.raca'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.especie'),
        ),
    ]
