# Generated by Django 4.1 on 2022-09-30 12:23

from django.db import migrations, models
import ecommerce.pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.pet.models.upload_image_formater),
        ),
    ]
