# Generated by Django 4.1 on 2022-09-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_remove_pet_racacachorro_remove_pet_racagato_pet_raca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raca',
            options={'ordering': ('raca',)},
        ),
    ]
