# Generated by Django 4.1 on 2022-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_anamnesemodel_obs_alter_anamnesemodel_boca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='obs',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Observações:'),
        ),
    ]
