# Generated by Django 4.1 on 2022-09-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_petmodel_delete_formpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unhas', models.CharField(choices=[('Normais', 'Normais'), ('Grandes', 'Grandes'), ('Encravadas', 'Encravadas'), ('Inflamadas', 'Inflamadas'), ('Infeccionadas', 'Infeccionadas')], max_length=100, verbose_name='Unhas')),
                ('ectoparasitas', models.CharField(choices=[('Pulgas', 'Pulgas'), ('Piolho', 'Piolho'), ('Carrapato', 'Carrapato'), ('Verme', 'Verme'), ('Miase', 'Miase')], max_length=100, verbose_name='Ectoparasitas')),
                ('peleInfeccionada', models.CharField(choices=[('Dermatite', 'Dermatite'), ('Micose', 'Micose')], max_length=100, verbose_name='Infecção na Pele')),
                ('peleOutros', models.CharField(choices=[('Oleosa', 'Oleosa'), ('Plurido', 'Plurido'), ('Seborea', 'Seborea')], max_length=100, verbose_name='Outros')),
                ('pelos', models.CharField(choices=[('Ressecado', 'Ressecado'), ('Danificado', 'Danificado')], max_length=100, verbose_name='Pelos')),
                ('pelosEstado', models.CharField(choices=[('Limpo', 'Limpo'), ('Pouco Sujo', 'Pouco Sujo'), ('Sujo', 'Sujo'), ('Muito Sujo', 'Muito Sujo'), ('Encardido', 'Encardido')], max_length=100, verbose_name='Estado do Pelo')),
                ('pelosCondicao', models.CharField(choices=[('Livre', 'Livre'), ('Bagunçado', 'Bagunçado'), ('Embaraçado', 'Embaraçado'), ('Embaraçado com bola reversível', 'Embaraçado com bola reversível'), ('Embaraçado com bola irreversível', 'Embaraçado com bola irreversível'), ('Crítico', 'Crítico')], max_length=100, verbose_name='Condição dos Pelos')),
                ('boca', models.CharField(choices=[('Gengivite', 'Gengivite'), ('Doença Periodontal', 'Doença Periodontal'), ('Lesões endodônticas', 'Lesões endodônticas')], max_length=100, verbose_name='Boca')),
                ('olhos', models.CharField(choices=[('Inflamados', 'Inflamados'), ('QueimadoGlaucoma', 'Glaucoma'), ('Catarata', 'Catarata'), ('Queimado', 'Queimado'), ('Alergia', 'Alergia'), ('Úlcera na Córnea', 'Úlcera na Córnea'), ('Uveíte', 'Uveíte'), ('Conjuntivite(Ceratoconjuntivite Seca)', 'Conjuntivite(Ceratoconjuntivite Seca)')], max_length=100, verbose_name='Olhos')),
                ('patas', models.CharField(choices=[('Calo', 'Calo'), ('Lesionados', 'Lesionados'), ('Infeccionado', 'Infeccionado'), ('Inflamados', 'Inflamados'), ('Bicho de pé', 'Bicho de pé')], max_length=100, verbose_name='Patas')),
                ('orelhas', models.CharField(choices=[('Infecção', 'Infecção'), ('Inflamação', 'Inflamação')], max_length=100, verbose_name='Orelhas')),
            ],
        ),
    ]
