# Generated by Django 4.1 on 2022-09-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_raca_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raca',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='raca',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='raca',
        ),
    ]
