# Generated by Django 4.1 on 2022-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_anamnesemodel_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesemodel',
            name='doenca',
            field=models.CharField(choices=[('Leishmaniose', 'Leishmaniose'), ('Doença Gastro Intestinal', 'Doença Gastro Intestinal'), ('Trauma Cutaneo', 'Trauma Cutaneo'), ('Hemorragia', 'Hemorragia')], default=None, max_length=100, verbose_name='Doenças:'),
        ),
    ]
