# Generated by Django 4.1 on 2022-09-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cliente_cpf_alter_cliente_telefone'),
        ('pet', '0004_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente'),
        ),
    ]
