# Generated by Django 4.1 on 2022-09-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_pet_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='pet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
