# Generated by Django 4.1 on 2022-09-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('pet', '0005_remove_raca_especie_remove_pet_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.especie'),
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.raca'),
        ),
    ]
