# Generated by Django 4.1 on 2022-09-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_peso_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='castracao',
            field=models.BooleanField(default=False, verbose_name='Castrado(a)'),
        ),
        migrations.AlterField(
            model_name='peso',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
