# Generated by Django 4.1 on 2022-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_anamnesemodel_doenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='boca',
            field=models.CharField(blank=True, choices=[('Gengivite', 'Gengivite'), ('Doença Periodontal', 'Doença Periodontal'), ('Lesões endodônticas', 'Lesões endodônticas')], max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='olhos',
            field=models.CharField(blank=True, choices=[('Inflamados', 'Inflamados'), ('QueimadoGlaucoma', 'Glaucoma'), ('Catarata', 'Catarata'), ('Queimado', 'Queimado'), ('Alergia', 'Alergia'), ('Úlcera na Córnea', 'Úlcera na Córnea'), ('Uveíte', 'Uveíte'), ('Conjuntivite(Ceratoconjuntivite Seca)', 'Conjuntivite(Ceratoconjuntivite Seca)')], max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='orelhas',
            field=models.CharField(blank=True, choices=[('Infecção', 'Infecção'), ('Inflamação', 'Inflamação')], max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='patas',
            field=models.CharField(blank=True, choices=[('Calo', 'Calo'), ('Lesionados', 'Lesionados'), ('Infeccionado', 'Infeccionado'), ('Inflamados', 'Inflamados'), ('Bicho de pé', 'Bicho de pé')], max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='unhas',
            field=models.CharField(blank=True, choices=[('Normais', 'Normais'), ('Grandes', 'Grandes'), ('Encravadas', 'Encravadas'), ('Inflamadas', 'Inflamadas'), ('Infeccionadas', 'Infeccionadas')], max_length=100, null=True, verbose_name=''),
        ),
    ]
