# Generated by Django 4.1 on 2022-10-03 12:57

from django.db import migrations, models
import ecommerce.pet.models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_pet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=ecommerce.pet.models.upload_image_formater, verbose_name='Foto do Pet')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='pet',
            name='photo',
        ),
    ]
