# Generated by Django 4.1 on 2022-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_anamnesemodel_boca_alter_anamnesemodel_olhos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesemodel',
            name='idficha',
            field=models.CharField(default=None, max_length=11, unique=True, verbose_name='Nº Ficha'),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='doenca',
            field=models.CharField(choices=[('Sem Doenças', 'Sem Doença'), ('Leishmaniose', 'Leishmaniose'), ('Doença Gastro Intestinal', 'Doença Gastro Intestinal'), ('Trauma Cutaneo', 'Trauma Cutaneo'), ('Hemorragia', 'Hemorragia')], default=None, max_length=100, verbose_name=''),
        ),
    ]
