# Generated by Django 4.1 on 2022-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
