# Generated by Django 4.1 on 2022-10-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_pet_photo_delete_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'ordering': ('pk',)},
        ),
    ]
