# Generated by Django 4.1 on 2022-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_alter_pet_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='obs',
            field=models.TextField(default='Sem anotações', verbose_name='Anotações'),
            preserve_default=False,
        ),
    ]
