# Generated by Django 4.1 on 2022-10-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0019_alter_peso_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peso',
            name='user',
        ),
    ]
