# Generated by Django 4.1 on 2022-10-27 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0020_remove_peso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='peso',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peso',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
    ]
