# Generated by Django 4.1 on 2022-11-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0024_remove_peso_pet_remove_peso_user_remove_raca_especie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='coloracao',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pelagem',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='temperamento',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type_pelo',
        ),
    ]
