# Generated by Django 4.1 on 2022-11-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especie', '0001_initial'),
        ('raca', '0001_initial'),
        ('pet', '0025_remove_pet_coloracao_remove_pet_pelagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='especie.especie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='raca.raca'),
            preserve_default=False,
        ),
    ]
