# Generated by Django 4.1 on 2022-11-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperamento', '0001_initial'),
        ('pelos', '0002_coloracao_pelagem'),
        ('pet', '0026_pet_especie_pet_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='coloracao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pelos.coloracao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='pelagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pelos.pelagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='temperamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='temperamento.temperamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='type_pelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pelos.pelos'),
            preserve_default=False,
        ),
    ]
