# Generated by Django 4.1 on 2022-11-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelos', '0002_coloracao_pelagem'),
        ('temperamento', '0001_initial'),
        ('raca', '0001_initial'),
        ('especie', '0001_initial'),
        ('pet', '0027_pet_coloracao_pet_pelagem_pet_temperamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='coloracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pelos.coloracao', verbose_name='Cor dos Pelos'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='especie.especie', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pelagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pelos.pelagem', verbose_name='Pelagem'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raca.raca', verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temperamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='temperamento.temperamento', verbose_name='Temperamento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type_pelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pelos.pelos', verbose_name='Pelos'),
        ),
    ]
