# Generated by Django 4.1 on 2022-11-03 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0028_alter_pet_coloracao_alter_pet_especie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='tutor',
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
