# Generated by Django 4.1 on 2022-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0031_alter_pet_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(default=1, max_length=2, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
