# Generated by Django 4.1 on 2022-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0033_alter_pet_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
    ]
