# Generated by Django 4.1 on 2022-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0034_alter_pet_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
