# Generated by Django 4.1 on 2022-11-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0035_alter_pet_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Idade'),
        ),
    ]
