# Generated by Django 4.1 on 2022-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0037_alter_pet_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
    ]
