# Generated by Django 4.1 on 2022-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100, unique=True, verbose_name='Espécie')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
