# Generated by Django 4.1 on 2022-09-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('status', models.CharField(blank=True, choices=[('a', 'Ativo'), ('i', 'Inativo')], max_length=1)),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unhas', models.CharField(choices=[('Normais', 'Normais'), ('Grandes', 'Grandes'), ('Encravadas', 'Encravadas'), ('Inflamadas', 'Inflamadas'), ('Infeccionadas', 'Infeccionadas')], max_length=100, verbose_name='')),
                ('ectoparasitas', models.CharField(choices=[('Sem Ectoparasitas', 'Sem Ectoparasitas'), ('Pulgas', 'Pulgas'), ('Piolho', 'Piolho'), ('Carrapato', 'Carrapato'), ('Verme', 'Verme'), ('Miase', 'Miase')], max_length=100, verbose_name='Ectoparasitas')),
                ('peleInfeccionada', models.CharField(choices=[('Normal', 'Normal'), ('Dermatite', 'Dermatite'), ('Micose', 'Micose')], max_length=100, verbose_name='Infecção na Pele')),
                ('peleOutros', models.CharField(choices=[('Normal', 'Normal'), ('Oleosa', 'Oleosa'), ('Plurido', 'Plurido'), ('Seborea', 'Seborea')], max_length=100, verbose_name='Outros')),
                ('pelos', models.CharField(choices=[('Hidratados', 'Hidratatos'), ('Ressecado', 'Ressecado'), ('Danificado', 'Danificado')], max_length=100, verbose_name='Pelos')),
                ('pelosEstado', models.CharField(choices=[('Limpo', 'Limpo'), ('Pouco Sujo', 'Pouco Sujo'), ('Sujo', 'Sujo'), ('Muito Sujo', 'Muito Sujo'), ('Encardido', 'Encardido')], max_length=100, verbose_name='Estado do Pelo')),
                ('pelosCondicao', models.CharField(choices=[('Livre', 'Livre'), ('Bagunçado', 'Bagunçado'), ('Embaraçado', 'Embaraçado'), ('Embaraçado com bola reversível', 'Embaraçado com bola reversível'), ('Embaraçado com bola irreversível', 'Embaraçado com bola irreversível'), ('Crítico', 'Crítico')], max_length=100, verbose_name='Condição dos Pelos')),
                ('boca', models.CharField(choices=[('Normal', 'Normal'), ('Gengivite', 'Gengivite'), ('Doença Periodontal', 'Doença Periodontal'), ('Lesões endodônticas', 'Lesões endodônticas')], max_length=100, verbose_name='')),
                ('olhos', models.CharField(choices=[('Normais', 'Normais'), ('Inflamados', 'Inflamados'), ('QueimadoGlaucoma', 'Glaucoma'), ('Catarata', 'Catarata'), ('Queimado', 'Queimado'), ('Alergia', 'Alergia'), ('Úlcera na Córnea', 'Úlcera na Córnea'), ('Uveíte', 'Uveíte'), ('Conjuntivite(Ceratoconjuntivite Seca)', 'Conjuntivite(Ceratoconjuntivite Seca)')], max_length=100, verbose_name='')),
                ('patas', models.CharField(choices=[('Normais', 'Normais'), ('Calo', 'Calo'), ('Lesionados', 'Lesionados'), ('Infeccionado', 'Infeccionado'), ('Inflamados', 'Inflamados'), ('Bicho de pé', 'Bicho de pé')], max_length=100, verbose_name='')),
                ('orelhas', models.CharField(choices=[('Infecção', 'Infecção'), ('Inflamação', 'Inflamação')], max_length=100, verbose_name='')),
                ('doenca', models.CharField(choices=[('Sem Doenças', 'Sem Doença'), ('Leishmaniose', 'Leishmaniose'), ('Doença Gastro Intestinal', 'Doença Gastro Intestinal'), ('Trauma Cutaneo', 'Trauma Cutaneo'), ('Hemorragia', 'Hemorragia')], max_length=100, verbose_name='')),
                ('obs', models.TextField(blank=True, max_length=400, null=True, verbose_name='')),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='ficha.controle')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
