# Generated by Django 4.1 on 2022-09-28 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0002_especie_alter_pet_options_remove_pet_apelido_and_more'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boca', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Condicao_pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelosCondicao', models.CharField(max_length=100, verbose_name='Condição dos Pelos')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Ectoparasitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ectoparasitas', models.CharField(max_length=100, verbose_name='Ectoparasitas')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Estado_pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelosEstado', models.CharField(max_length=100, verbose_name='Estado do Pelo')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Infec_pele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peleInfeccionada', models.CharField(max_length=100, verbose_name='Infecção na Pele')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Olhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olhos', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Orelhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orelhas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Patas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Pele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pele', models.CharField(max_length=100, verbose_name='Outros')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelos', models.CharField(max_length=100, verbose_name='Pelos')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Unhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unhas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='controle',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='peleOutros',
        ),
        migrations.AddField(
            model_name='ficha',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichaPets', to='pet.pet'),
        ),
        migrations.DeleteModel(
            name='Controle',
        ),
        migrations.AddField(
            model_name='ficha',
            name='pele',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ficha.pele'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='boca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.boca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='doenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.doenca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ectoparasitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.ectoparasitas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='olhos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.olhos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='orelhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.orelhas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='patas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.patas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.infec_pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosCondicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.condicao_pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.estado_pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='unhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.unhas'),
        ),
    ]
