# Generated by Django 4.1 on 2022-09-23 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0001_initial'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='controle',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichaPets', to='pet.pet'),
        ),
        migrations.DeleteModel(
            name='Controle',
        ),
        migrations.AddField(
            model_name='ficha',
            name='prontuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.prontuario'),
        ),
    ]
