# Generated by Django 4.1 on 2022-09-09 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='controle',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichaPets', to='pet.pet'),
        ),
        migrations.DeleteModel(
            name='Controle',
        ),
    ]
