# Generated by Django 4.1 on 2022-09-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_create_remove_ficha_controle_alter_ficha_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='created',
        ),
    ]
