# Generated by Django 4.1 on 2022-09-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_prontuario_remove_ficha_controle_alter_ficha_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pele', models.CharField(max_length=100, verbose_name='Outros')),
                ('ectoparasitas', models.CharField(max_length=100, verbose_name='Ectoparasitas')),
                ('peleInfeccionada', models.CharField(max_length=100, verbose_name='Infecção na Pele')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelos', models.CharField(max_length=100, verbose_name='Pelos')),
                ('pelosEstado', models.CharField(max_length=100, verbose_name='Estado do Pelo')),
                ('pelosCondicao', models.CharField(max_length=100, verbose_name='Condição dos Pelos')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='boca',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ectoparasitas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='olhos',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='orelhas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='patas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='peleInfeccionada',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='peleOutros',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pelosCondicao',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pelosEstado',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='unhas',
        ),
        migrations.AddField(
            model_name='ficha',
            name='pele',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.pelos'),
        ),
    ]
