# Generated by Django 4.1 on 2022-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_pele_pelos_remove_ficha_boca_remove_ficha_doenca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ectoparasitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ectoparasitas', models.CharField(max_length=100, verbose_name='Ectoparasitas')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Infec_pele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peleInfeccionada', models.CharField(max_length=100, verbose_name='Infecção na Pele')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(
            model_name='pele',
            name='ectoparasitas',
        ),
        migrations.RemoveField(
            model_name='pele',
            name='peleInfeccionada',
        ),
    ]
