# Generated by Django 4.1 on 2022-09-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_ectoparasitas_infec_pele_remove_pele_ectoparasitas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenca', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
