# Generated by Django 4.1 on 2022-10-31 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_caracteristicas_raca_especie_raca_peso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristicas_raca',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='raca',
            name='caracteristicas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ficha.caracteristicas_raca'),
            preserve_default=False,
        ),
    ]
