# Generated by Django 4.1 on 2022-10-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_alter_caracteristicas_raca_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raca',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='caracteristicas_raca',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ficha.raca'),
            preserve_default=False,
        ),
    ]
