# Generated by Django 4.1 on 2022-10-31 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orelhas', '0001_initial'),
        ('doenca', '0001_initial'),
        ('pele', '0001_initial'),
        ('pelos', '0001_initial'),
        ('boca', '0001_initial'),
        ('olhos', '0001_initial'),
        ('unhas', '0001_initial'),
        ('ficha', '0006_remove_raca_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristicas_raca',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='peso',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='peso',
            name='user',
        ),
        migrations.RemoveField(
            model_name='raca',
            name='especie',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='boca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boca.boca', verbose_name='Boca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='doenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doenca.doenca', verbose_name='Doença'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ectoparasitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pele.ectoparasitas', verbose_name='Ectoparasitas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='olhos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olhos.olhos', verbose_name='Olhos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='orelhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orelhas.orelhas', verbose_name='Orelhas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='patas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patas.patas', verbose_name='Patas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pele.pele', verbose_name='Tipo de Pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pele.infec_pele', verbose_name='Doença na Pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelos.pelos', verbose_name='Pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosCondicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelos.condicao_pelos', verbose_name='Condição dos Pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelos.estado_pelos', verbose_name='Estado dos Pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='unhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhas.unhas', verbose_name='Unhas'),
        ),
        migrations.DeleteModel(
            name='Boca',
        ),
        migrations.DeleteModel(
            name='Caracteristicas_Raca',
        ),
        migrations.DeleteModel(
            name='Condicao_pelos',
        ),
        migrations.DeleteModel(
            name='Doenca',
        ),
        migrations.DeleteModel(
            name='Ectoparasitas',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='Estado_pelos',
        ),
        migrations.DeleteModel(
            name='Infec_pele',
        ),
        migrations.DeleteModel(
            name='Olhos',
        ),
        migrations.DeleteModel(
            name='Orelhas',
        ),
        migrations.DeleteModel(
            name='Patas',
        ),
        migrations.DeleteModel(
            name='Pele',
        ),
        migrations.DeleteModel(
            name='Pelos',
        ),
        migrations.DeleteModel(
            name='Peso',
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
        migrations.DeleteModel(
            name='Unhas',
        ),
    ]
