# Generated by Django 4.1 on 2022-09-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_condicao_pelos_estado_pelos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boca', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Olhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olhos', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Orelhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orelhas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Patas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Unhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unhas', models.CharField(max_length=100, verbose_name='')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='doenca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.doenca'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ectoparasitas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.ectoparasitas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.infec_pele'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pelosCondicao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.condicao_pelos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pelosEstado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.estado_pelos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='boca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.boca'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='olhos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.olhos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='orelhas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.orelhas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='patas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.patas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='unhas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha.unhas'),
        ),
    ]
