# Generated by Django 4.1 on 2022-09-27 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0007_boca_olhos_orelhas_patas_unhas_ficha_doenca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='prontuario',
        ),
        migrations.AddField(
            model_name='ficha',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='funcionario',
            field=models.ForeignKey(blank=True, default=27, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='boca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.boca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='doenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.doenca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ectoparasitas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.ectoparasitas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='olhos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.olhos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='orelhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.orelhas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='patas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.patas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.infec_pele'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosCondicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.condicao_pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='pelosEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.estado_pelos'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='unhas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.unhas'),
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
    ]
