# Generated by Django 4.1 on 2022-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orelhas', '0001_initial'),
        ('doenca', '0001_initial'),
        ('unhas', '0001_initial'),
        ('pelos', '0002_coloracao_pelagem'),
        ('pele', '0002_alter_infec_pele_peleinfeccionada_and_more'),
        ('boca', '0001_initial'),
        ('olhos', '0001_initial'),
        ('patas', '0001_initial'),
        ('ficha', '0007_remove_caracteristicas_raca_raca_remove_peso_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='boca',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ectoparasitas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='olhos',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='orelhas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='patas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pele',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='peleInfeccionada',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pelos',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pelosCondicao',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pelosEstado',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='unhas',
        ),
        migrations.AddField(
            model_name='ficha',
            name='boca',
            field=models.ManyToManyField(to='boca.boca', verbose_name='Boca'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='doenca',
            field=models.ManyToManyField(to='doenca.doenca', verbose_name='Doença'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='ectoparasitas',
            field=models.ManyToManyField(to='pele.ectoparasitas', verbose_name='Ectoparasitas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='olhos',
            field=models.ManyToManyField(to='olhos.olhos', verbose_name='Olhos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='orelhas',
            field=models.ManyToManyField(to='orelhas.orelhas', verbose_name='Orelhas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='patas',
            field=models.ManyToManyField(to='patas.patas', verbose_name='Patas'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pele',
            field=models.ManyToManyField(to='pele.pele', verbose_name='Tipo de Pele'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ManyToManyField(to='pele.infec_pele', verbose_name='Doença na Pele'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pelos',
            field=models.ManyToManyField(to='pelos.pelos', verbose_name='Pelos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pelosCondicao',
            field=models.ManyToManyField(to='pelos.condicao_pelos', verbose_name='Condição dos Pelos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='pelosEstado',
            field=models.ManyToManyField(to='pelos.estado_pelos', verbose_name='Estado dos Pelos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='unhas',
            field=models.ManyToManyField(to='unhas.unhas', verbose_name='Unhas'),
        ),
    ]
