# Generated by Django 4.1 on 2022-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pele', '0006_rename_doenca_doencapele_nome'),
        ('ficha', '0010_remove_ficha_peleinfeccionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='peleInfeccionada',
            field=models.ManyToManyField(to='pele.doencapele', verbose_name='Doença na Pele'),
        ),
    ]
