# Generated by Django 4.1 on 2022-11-10 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patas', '0002_rename_patas_patas_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0031_alter_pet_tutor'),
        ('olhos', '0002_rename_olhos_olhos_nome'),
        ('unhas', '0002_rename_unhas_unhas_nome'),
        ('pelos', '0003_rename_coloracao_coloracao_nome_and_more'),
        ('pele', '0006_rename_doenca_doencapele_nome'),
        ('orelhas', '0002_rename_orelhas_orelhas_nome'),
        ('boca', '0002_rename_boca_boca_nome'),
        ('doenca', '0002_rename_doenca_doenca_nome'),
        ('ficha', '0011_ficha_peleinfeccionada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ficha',
            new_name='Anamnese',
        ),
    ]
