# Generated by Django 4.1.3 on 2022-11-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_ficha_anamnese'),
        ('ficha', '0012_rename_ficha_anamnese'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichaBanho', to='services.ficha'),
        ),
    ]
