# Generated by Django 4.1.3 on 2022-11-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_anamnese_ficha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='ficha',
        ),
    ]
