# Generated by Django 4.1.3 on 2022-11-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_ficha_anamnese'),
        ('ficha', '0014_remove_anamnese_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banhoEtosa', to='services.ficha'),
        ),
    ]
