# Generated by Django 4.1 on 2022-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
