# Generated by Django 4.1 on 2022-10-10 12:34

from django.db import migrations, models
import ecommerce.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=ecommerce.accounts.models.upload_image_formater, verbose_name='Foto de Perfil'),
        ),
    ]
