# Generated by Django 4.1 on 2022-10-18 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('MedicoVet', 'Médico Veterinário'), ('Colaborador', 'Colaborador'), ('Cliente', 'Cliente')], default=1, max_length=50, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
