# Generated by Django 4.1 on 2022-10-19 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_remove_funcionario_email_remove_funcionario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('MedicoVet', 'Médico Veterinário'), ('Colaborador', 'Colaborador'), ('Cliente', 'Cliente')], default='cliente', max_length=50, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
