# Generated by Django 4.1 on 2022-10-19 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_cliente_cargo_cliente_status_alter_cliente_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Profile',
        ),
    ]
