# Generated by Django 4.1 on 2022-10-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endereço',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.endereco'),
        ),
    ]
