# Generated by Django 4.1 on 2022-10-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_endereço'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
