# Generated by Django 4.1 on 2022-10-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_endereço_profile_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
