# Generated by Django 4.1 on 2022-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_endereco_endereco_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='Endereço',
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(default='sem complemento', max_length=200, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco',
            field=models.CharField(default='Endereço vazio', max_length=200, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='BAIRRO'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='CIDADE'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC')], max_length=2, verbose_name='UF'),
        ),
    ]
