# Generated by Django 4.1 on 2022-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_endereco_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aniversario',
            field=models.DateField(default='1111-11-11', verbose_name='Aniversário'),
            preserve_default=False,
        ),
    ]
