# Generated by Django 4.1 on 2022-11-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('MedicoVet', 'Médico Veterinário'), ('Colaborador', 'Colaborador'), ('Cliente', 'Cliente')], default='Cliente', max_length=50, verbose_name='Cargo'),
        ),
    ]
