# Generated by Django 4.1.3 on 2022-11-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cargo',
        ),
    ]
