# Generated by Django 4.1.3 on 2022-11-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_profile_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Medico Veterinario', 'Médico Veterinário'), ('Colaborador', 'Colaborador'), ('Cliente', 'Cliente')], max_length=50, verbose_name='Cargo'),
        ),
    ]
