# Generated by Django 4.1 on 2022-10-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao_pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelosCondicao', models.CharField(max_length=100, verbose_name='Condição dos Pelos')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Estado_pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelosEstado', models.CharField(max_length=100, verbose_name='Estado do Pelo')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Pelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelos', models.CharField(max_length=100, verbose_name='Pelos')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
