# Generated by Django 4.1 on 2022-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coloracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coloracao', models.CharField(max_length=50, verbose_name='Coloração')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Pelagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelagem', models.CharField(max_length=50, verbose_name='Pelagem')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
